# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: [en, fr]
    profile_directory: '%kernel.project_dir%/public/uploads/profile'
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\UserController:
        arguments:
            $security: '@security'
            $session: '@session'

    App\EventListener\LocaleListener:
        arguments:
            $defaultLocale: '%locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\Tests\:
        resource: '../tests/'
        exclude: 
            - '../tests/Entity'
            - '../tests/bootstrap.php'
            - '../tests/'  # Exclure les tests pour Ã©viter que Symfony les traite comme des services

            
    App\Command\SendNewsletterCommand:
        tags: ['console.command']
        
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones